services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: porthub_api_prod
    container_name: porthub_api_prod
    environment:
      - API_DEBUG=False
      - RATHOLE_SERVER_CONFIG_PATH=/runtime/rathole/server.toml
      - TRAEFIK_DYNAMIC_CONFIG_PATH=/runtime/traefik/traffic-routes.yml
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./api:/app
      - rathole_config:/runtime/rathole
      - traefik_routes:/runtime/traefik
    restart: always
    networks:
      - porthub

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    image: porthub_ui_prod
    container_name: porthub_ui_prod
    env_file:
      - ./.env
    environment:
      - BUILD_ENV=prod
    restart: always
    depends_on:
      - api
    networks:
      - porthub

  proxy:
    image: nginx:1.19-alpine
    container_name: porthub_proxy
    env_file:
      - ./.env
    ports:
      - "8345:80"
      - "8346:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./proxy/certificate/server.crt:/etc/ssl/certs/server.crt
      - ./proxy/certificate/server.key:/etc/ssl/certs/server.key
    restart: always
    depends_on:
      - api
      - ui
    networks:
      - porthub

  rathole:
    image: archef2000/rathole:latest
    command: -s /runtime/rathole/server.toml
    container_name: porthub_rathole
    network_mode: host
    volumes:
      - rathole_config:/runtime/rathole
    restart: always
    depends_on:
      - api

  traefik:
    image: traefik:v3.0
    container_name: porthub_traefik_prod
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--accesslog.filepath=/shared/access.log"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_routes:/dynamic
      - traefik_shared:/shared
    restart: always
    networks:
      - porthub

  firewall:
    build:
      context: ./firewall
      dockerfile: Dockerfile
    image: porthub_firewall_prod
    container_name: porthub_firewall_prod
    env_file:
      - ./.env
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - FW_DEBUG=False
    volumes:
      - firewall_state:/state
    restart: always

networks:
  porthub:
    name: porthub

volumes:
  rathole_config:
  firewall_state:
  traefik_routes:
  traefik_shared:
